windows_packages:
  - Microsoft.VisualStudioCode
  - Anthropic.ClaudeCode
  - Casey.Just
  - DoltHub.Dolt
  - Neovim.Neovim
  - BurntSushi.ripgrep.MSVC
  - sharkdp.fd
  - JesseDuffield.lazygit
  - OpenJS.NodeJS.LTS
  - zig.zig
