- hosts: localhost

  pre_tasks:
    - name: "Load variables"
      ansible.builtin.include_vars:
        file: "config/config.yml"

  tasks:
    - name: "Apply system role"
      ansible.builtin.import_role:
        name: "system"
      vars:
        apply_bluetooth: "{{ role_system_bt }}"
        apply_drivers: "{{ role_system_drivers }}"
        apply_sound: "{{ role_system_sound }}"
        apply_network: "{{ role_system_network }}"
        apply_docker: "{{ role_system_docker }}"
        apply_wsl: "{{ role_system_wsl }}"
      when: role_system

    - name: "Apply WAC role"
      ansible.builtin.import_role:
        name: "wac"

    - name: "Apply shell role"
      ansible.builtin.import_role:
        name: "shell"
      when: role_shell

    - name: "Apply desktop environment role"
      ansible.builtin.import_role:
        name: "de"
      when: "{{ role_de }}"

    - name: "Apply packages role"
      ansible.builtin.import_role:
        name: "packages"
      when: "{{ role_packages }}"

  handlers:
    - import_tasks: handlers/main.yml

- hosts: windows
  ignore_unreachable: yes

  pre_tasks:
    - name: "Load variables"
      ansible.builtin.include_vars:
        file: "config/config.yml"

    - name: "Check if Windows management is enabled"
      ansible.builtin.set_fact:
        windows_enabled: "{{ role_system_wsl_windows | default(false) }}"

  tasks:
    - name: "Apply packages role for Windows"
      ansible.builtin.import_role:
        name: "packages"
      when: 
        - windows_enabled
        - role_packages
        - ansible_facts is defined
        - ansible_facts.system is defined
