- name: Install Nix Package Manager
  block:
    - name: "Msg"
      debug:
        msg: "The following task can take a long time, don't close the session."

    - name: Install Nix Package Manager [1/3]
      shell: |
        set -o pipefail &&
        curl -L https://nixos.org/nix/install | sh
      args:
        executable: /bin/bash
        creates: "/nix/var/nix/profiles/default/bin/nix"
      
    # TODO: need to restart shell session?

    - name: Install Nix Package Manager [2/3]
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.config/nix/nix.conf"
        line: experimental-features = nix-command flakes
        create: true

- name: Install Homebrew
  shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    executable: /bin/bash
    creates: /opt/homebrew/bin/brew
